### ISSUE TITLE
BOM Search

### ISSUE THREAD

**Issue by rcastle1** [badgerloop-software/BOM-Webapp#7]
I went to search for a purchase request and got this error after searching "Amazon" 

Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.4.29 (Ubuntu) Server at finance.badgerloop.com Port 443

Also, is it possible to add support for viewing the purchased and in purchased items? I frequently ctrl + f for components in the BOM and I only see a tab for viewing purchase requests, rather than the fully BOM

**Comment by EUdds** [comment]
Fixed
