### ISSUE TITLE
Add sub categories

### ISSUE THREAD

**Issue by rcastle1** [badgerloop-software/BOM-Webapp#9]
Can you add extra categories like project, counts toward pod cost, need date?

**Comment by EUdds** [comment]
@rcastle1 do you think need date and specific project could be taken care of by the comments?

**Comment by rcastle1** [comment]
I think it would be good to have those fields set explicitly, otherwise they won't get filled out most of the time.

**Comment by EUdds** [comment]
Feature added in the latest update
